# Generated by Django 6.0.1 on 2026-02-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('BCOM', 'B.Com'), ('BA_TAMIL', 'BA Tamil'), ('BA_ENGLISH', 'BA English'), ('BA_HISTORY', 'BA History'), ('BSC_PSY', 'BSc Psychology'), ('BSC_PHY', 'BSc Physics'), ('BSC_CHEM', 'BSc Chemistry'), ('BSC_MATHS', 'BSc Maths'), ('BSC_ZOO', 'BSc Zoology'), ('BSC_MICRO', 'BSc Micro Biology')], max_length=20, null=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('I', 'I YEAR'), ('II', 'II YEAR'), ('III', 'III YEAR')], max_length=5, null=True, verbose_name='Year'),
        ),
    ]
