# Generated by Django 6.0.1 on 2026-02-11 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_student_department_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('BCS_CS', 'BSc Computer Science'), ('BCOM', 'B.Com'), ('BA_TAMIL', 'BA Tamil'), ('BA_ENGLISH', 'BA English'), ('BA_HISTORY', 'BA History'), ('BSC_PSY', 'BSc Psychology'), ('BSC_PHY', 'BSc Physics'), ('BSC_CHEM', 'BSc Chemistry'), ('BSC_MATHS', 'BSc Maths'), ('BSC_ZOO', 'BSc Zology'), ('BSC_MICRO', 'BSc Micro Biology')], max_length=20, null=True, verbose_name='Department'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('period', models.CharField(choices=[('1', 'First Period (8:00-9:00)'), ('2', 'Second Period (9:00-10:00)'), ('3', 'Third Period (10:15-11:15)'), ('4', 'Fourth Period (11:15-12:15)'), ('5', 'Fifth Period (12:15-1:15)')], max_length=1)),
                ('status', models.CharField(default='Present', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'date', 'period')},
            },
        ),
    ]
