# Generated by Django 6.0.1 on 2026-02-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0005_alter_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_order', models.CharField(choices=[('A', 'Order A'), ('B', 'Order B'), ('C', 'Order C'), ('D', 'Order D'), ('E', 'Order E'), ('F', 'Order F')], max_length=1)),
                ('period', models.CharField(choices=[('1', 'First Period'), ('2', 'Second Period'), ('3', 'Third Period'), ('4', 'Fourth Period'), ('5', 'Fifth Period')], max_length=1)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('day_order', 'period')},
            },
        ),
    ]
