# Generated by Django 6.0.1 on 2026-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0006_orderschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Email address for daily attendance alerts and weekly summaries.', max_length=254, null=True, verbose_name="Parent's Email"),
        ),
    ]
