# Generated by Django 6.0.1 on 2026-03-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_student_parent_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('period', models.CharField(max_length=10)),
                ('finalized_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'period')},
            },
        ),
    ]
