# Generated by Django 6.0.1 on 2026-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_periodfinalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('1', 'First Period'), ('2', 'Second Period'), ('3', 'Third Period'), ('4', 'Fourth Period'), ('5', 'Fifth Period')], max_length=1),
        ),
    ]
