# Generated by Django 6.0.1 on 2026-03-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_alter_attendance_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, help_text='Used as password (DD/MM/YYYY)', null=True, verbose_name='Date of Birth'),
        ),
    ]
