# Generated by Django 6.0.1 on 2026-04-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0010_student_dob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='department',
            field=models.CharField(choices=[('BCS_CS', 'BSc Computer Science'), ('BCOM', 'B.Com'), ('BA_TAMIL', 'BA Tamil'), ('BA_ENGLISH', 'BA English'), ('BA_HISTORY', 'BA History'), ('BSC_PSY', 'BSc Psychology'), ('BSC_PHY', 'BSc Physics'), ('BSC_CHEM', 'BSc Chemistry'), ('BSC_MATHS', 'BSc Maths'), ('BSC_ZOO', 'BSc Zology'), ('BSC_MICRO', 'BSc Micro Biology')], default='BCS_CS', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='orderschedule',
            unique_together={('day_order', 'period', 'department')},
        ),
    ]
